//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.30 at 06:21:10 PM IST 
//


package xmlParser;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the https.compute_ind_.west_1_jiocloudservices_com.doc._2016_03_01 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: https.compute_ind_.west_1_jiocloudservices_com.doc._2016_03_01
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CreateVolumeResponse }
     * 
     */
    public CreateVolumeResponse createCreateVolumeResponse() {
        return new CreateVolumeResponse();
    }
    
    public DeleteVolumeResponse createDeleteVolumeResponse() {
        return new DeleteVolumeResponse();
    }

    public DescribeVolumesResponse createDescribeVolumesResponse() {
        return new DescribeVolumesResponse();
    }

    /**
     * Create an instance of {@link DescribeVolumesResponse.VolumeSet }
     * 
     */
    public DescribeVolumesResponse.VolumeSet createDescribeVolumesResponseVolumeSet() {
        return new DescribeVolumesResponse.VolumeSet();
    }

    /**
     * Create an instance of {@link DescribeVolumesResponse.VolumeSet.Item }
     * 
     */
    public DescribeVolumesResponse.VolumeSet.Item createDescribeVolumesResponseVolumeSetItem() {
        return new DescribeVolumesResponse.VolumeSet.Item();
    }
    
    public CreateSnapshotResponse createCreateSnapshotResponse() {
        return new CreateSnapshotResponse();
    }

    public DeleteSnapshotResponse createDeleteSnapshotResponse() {
        return new DeleteSnapshotResponse();
    }
    
    /**
     * Create an instance of {@link DescribeSnapshotsResponse }
     * 
     */
    public DescribeSnapshotsResponse createDescribeSnapshotsResponse() {
        return new DescribeSnapshotsResponse();
    }

    /**
     * Create an instance of {@link DescribeSnapshotsResponse.SnapshotSet }
     * 
     */
    public DescribeSnapshotsResponse.SnapshotSet createDescribeSnapshotsResponseSnapshotSet() {
        return new DescribeSnapshotsResponse.SnapshotSet();
    }

    /**
     * Create an instance of {@link DescribeSnapshotsResponse.SnapshotSet.Item }
     * 
     */
    public DescribeSnapshotsResponse.SnapshotSet.Item createDescribeSnapshotsResponseSnapshotSetItem() {
        return new DescribeSnapshotsResponse.SnapshotSet.Item();
    }

}
