//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.30 at 06:21:10 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://compute.jiocloudservices.com/doc/2016-03-01/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package https.compute_ind_.west_1_jiocloudservices_com.doc._2016_03_01;

